services:

  php:
    container_name: "php-fpm"
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Symfony Config
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
      - APP_DEBUG=${APP_DEBUG}
    volumes:
      - ${APP_FOLDER}:/var/www
    networks:
      - app_network

  nginx:
    container_name: "nginx"
    environment:
      HOSTNAME: ${HOSTNAME}
    build:
      context: ./docker/nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - app_network

  mysql:
    image: mysql:8.4
    container_name: "mysql"
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DATABASE_USER --password=$$DATABASE_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - app_network

  phpmyadmin:
    depends_on:
      mysql:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: "phpmyadmin"
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USER: ${PHPMYADMIN_USER}
      MYSQL_ROOT_PASSWORD: ${PHPMYADMIN_PASSWORD}
    networks:
      - app_network

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"

networks:
  app_network:
    driver: bridge